In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, InputLayer
from keras.regularizers import L1L2, l2, l1
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D
from custom_pooling import RMSPooling2D
from keras.optimizers import SGD, Adam
from keras.layers import LeakyReLU
#from data import BALANCE_WEIGHTS
from keras.preprocessing.image import ImageDataGenerator
from sklearn.utils import class_weight
from sklearn.metrics import confusion_matrix, classification_report
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
#import os
from datetime import datetime as dt
from custom_loss import WeightedCategoricalCrossEntropy
from VCM import VCM
from QWK import QWK
import keras.backend as K
from Fractional_MAXPOOL import FractionalPooling2D

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

In [2]:
def get_experiment_id():
    time_str = dt.now().strftime('%Y-%m-%d-%H-%M-%S')
    experiment_id = 'base_{}'.format(time_str)
    return experiment_id
p_ratio=[1.0, 1.44, 1.73, 1.0]

model = Sequential()


model.add(Conv2D(16, (5, 5), activation='linear', input_shape=(300, 300, 3)))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(16, (5, 5), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(Dense(8,activation='tanh', kernel_regularizer=regularizers.l2(0.0001)))
#model.add(LeakyReLU(alpha=0.01))
model.add(FractionalPooling2D(pool_ratio=(1, 1.8, 1.8, 1),pseudo_random = True,overlap=True))

model.add(Conv2D(16, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(16, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(Dense(8,activation='tanh', kernel_regularizer=regularizers.l2(0.0001)))
#model.add(FractionalPooling2D(pool_ratio=(1, 1.8, 1.8, 1),pseudo_random = True,overlap=True))

#model.add(LeakyReLU(alpha=0.01))


model.add(Conv2D(16, (5, 5), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(16, (5, 5), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(Dense(8,activation='tanh', kernel_regularizer=regularizers.l2(0.0001)))
#model.add(LeakyReLU(alpha=0.01))


model.add(FractionalPooling2D(pool_ratio=(1, 1.8, 1.8, 1),pseudo_random = True,overlap=True))

model.add(Conv2D(16, (5, 5), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(16, (5, 5), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(InputLayer(input_tensor=tf.nn.fractional_max_pool(model.layers[1].output, p_ratio)[0]))
#model.add(Dense(8,activation='tanh', kernel_regularizer=regularizers.l2(0.0001)))
#model.add(LeakyReLU(alpha=0.01))

model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(Dense(8,activation='tanh', kernel_regularizer=regularizers.l2(0.0001)))
#model.add(LeakyReLU(alpha=0.01))          
model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(Dense(8,activation='tanh', kernel_regularizer=regularizers.l2(0.0001)))
#model.add(LeakyReLU(alpha=0.01))
#model.add(FractionalPooling2D(pool_ratio=(1, 1.8, 1.8, 1),pseudo_random = True,overlap=True))

model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(Dense(8,activation='tanh', kernel_regularizer=regularizers.l2(0.0001)))
model.add(FractionalPooling2D(pool_ratio=(1, 1.7, 1.7, 1),pseudo_random = True,overlap=True))

model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(32, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(InputLayer(input_tensor=tf.nn.fractional_max_pool(model.layers[1].output, p_ratio)[0]))
#model.add(FractionalPooling2D(pool_ratio=(1, 1.8, 1.8, 1),pseudo_random = True,overlap=True))

model.add(Conv2D(64, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(64, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(FractionalPooling2D(pool_ratio=(1, 1.7, 1.7, 1),pseudo_random = True,overlap=True))
model.add(Conv2D(64, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(64, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))


model.add(Conv2D(64, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
model.add(Conv2D(64, (3, 3), activation='linear'))
model.add(LeakyReLU(alpha=0.01))
#model.add(InputLayer(input_tensor=tf.nn.fractional_max_pool(model.layers[1].output, p_ratio)[0]))

#model.add(MaxPooling2D(pool_size=1))




model.add(FractionalPooling2D(pool_ratio=(1, 1.7, 1.7, 1),pseudo_random = True,overlap=True))

model.add(Flatten())


#chnaged from 10 to 5 because an error 
model.add(Dense(3, activation='softmax'))

sgd = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
model.count_params()
#adam = Adam(lr=0.0005, decay=1e-6)
#rmsprop
#Mloss = WeightedCategoricalCrossEntropy({0: 0.4125861396437394, 1: 1.4918664786083686, 2: 0.690426457789382, 3: 3.9541433021806855, 4: 4.885604311008468})
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['acc','binary_accuracy','mae'])
model.summary()
loss_no_weight_decay = model.total_loss - sum(model.losses)
model.metrics_tensors.append(loss_no_weight_decay)
model.metrics_names.append('loss_no_weight_decay')
#############################################################################################
#############################################################################################
#############################################################################################
#############################################################################################
#Preparing Data Augmentation Configuration 
train_datagen = ImageDataGenerator(
        rescale=1./255,
#        featurewise_center=True,
 #       samplewise_center=True,
        shear_range=0,
        zoom_range=0.0,#[1 / 1.15, 1.15],
        horizontal_flip=False,#True,
        rotation_range=0)#90,
#        validation_split=0.2)
"""
For the test set only rescale should be made 
"""
test_datagen = ImageDataGenerator(rescale=1./255)
valid_datagen = ImageDataGenerator(rescale=1./255)


train_generator = train_datagen.flow_from_directory(
    directory=r"/media/husam/Data/ROP_EXp/three_class/train",
    target_size=(300, 300),
    color_mode="rgb",
    batch_size=64,
    class_mode="categorical",
    shuffle=True,
    seed=42)
#    subset="training")
#    save_to_dir="D:/Separating Images into subfolders/train_augmented")


#print(train_generator.class_indices)

valid_generator = valid_datagen.flow_from_directory(
    directory=r"/media/husam/Data/ROP_EXp/three_class/vald",
    target_size=(300, 300),
    color_mode="rgb",
    batch_size=64,
    class_mode="categorical",
    shuffle=True,
    seed=42)
#    subset="validation")
#    save_to_dir="D:/Separating Images into subfolders/val_augmented"


test_generator = test_datagen.flow_from_directory(
    directory=r"/media/husam/Data/ROP_EXp/three_class/test",
    target_size=(300, 300),
    color_mode="rgb",
    batch_size=1,
    class_mode="categorical",
    shuffle=False,
    seed=42)
#    save_to_dir="D:/Separating Images into subfolders/test_augmented")


# Fitting/Training the model
STEP_SIZE_TRAIN=train_generator.n//train_generator.batch_size
STEP_SIZE_VALID=valid_generator.n//valid_generator.batch_size
experiment_id = get_experiment_id()
callbacks = [
    QWK(valid_generator, STEP_SIZE_VALID),
    EarlyStopping(monitor='val_acc', patience=50, min_delta=0.001, verbose=1),
    ModelCheckpoint(experiment_id + "-val_kapa_checkpoint.hdf5", monitor='val_kappa', verbose=1, save_best_only=True, mode='max'),
    ReduceLROnPlateau(monitor='val_acc', factor=0.5, patience=7, verbose=1, mode='auto', min_delta=0.001, cooldown=0, min_lr=1e-7),
    VCM(valid_generator,STEP_SIZE_VALID)
    
]

class_weight_list = class_weight.compute_class_weight('balanced', np.unique(train_generator.classes), train_generator.classes)
class_weights = dict(zip(np.unique(train_generator.classes), class_weight_list))

history=model.fit_generator(generator=train_generator,
                    steps_per_epoch=STEP_SIZE_TRAIN,
                    validation_data=valid_generator,
                    validation_steps=STEP_SIZE_VALID,
                    class_weight=class_weights,
                    callbacks=callbacks,
                    epochs=50  
)


# Evaluating the model 
#predicting output
#reseting the test generator before calling predict_generator, in order not to get weird output
test_generator.reset()
#test_imgs, test_labels = next(test_generator)

y_pred = model.predict_generator(test_generator, verbose=1,steps=len(test_generator))

score = model.evaluate_generator(generator=test_generator, verbose=1,steps=len(test_generator))
print('Test loss:', score[0])
print('Test accuracy:', score[1])

#y_pred =


y_pred = np.argmax(y_pred, axis=1) #multiple categories
# mapping the labels to its classes 
labels = (train_generator.class_indices)
labels = dict((v,k) for k,v in labels.items())
predictions = [labels[k] for k in y_pred]

y_true = (test_generator.classes)
#confusion Matrix and Classification Report
# generator.classes gives you the truth label y_true
print('Confusion Matrix')
cm = confusion_matrix(y_true, y_pred)

print(cm)

print('Classification Report')
target_names = ['0', '1', '2']
print(classification_report(y_true, y_pred, target_names=target_names))



Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 296, 296, 16)      1216      
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 296, 296, 16)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 292, 292, 16)      6416      
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 292, 292, 16)      0         
_________________________________________________________________
fractional_pooling2d_1 (Frac (None, 162, 162, 16)      0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 160, 160, 16)      2320      
_________________________________________________________________
leaky_re_lu_3 (LeakyReLU)    (None, 160, 160, 16)     

9/9 [==============================] - 19s 2s/step - loss: 1.1277 - acc: 0.4624 - binary_accuracy: 0.6667 - mean_absolute_error: 0.4444 - loss_no_weight_decay: 1.1277 - val_loss: 1.0985 - val_acc: 0.5000 - val_binary_accuracy: 0.6667 - val_mean_absolute_error: 0.4444 - val_loss_no_weight_decay: 1.0985
— val_kappa: 0.0 

Epoch 00003: val_kappa did not improve from 0.00000
Confusion matrix: 
 [[22  0  0]
 [ 6  0  0]
 [24  0  0]]
Epoch 4/50
9/9 [==============================] - 19s 2s/step - loss: 1.0666 - acc: 0.5160 - binary_accuracy: 0.6667 - mean_absolute_error: 0.4444 - loss_no_weight_decay: 1.0666 - val_loss: 1.0982 - val_acc: 0.5192 - val_binary_accuracy: 0.6667 - val_mean_absolute_error: 0.4443 - val_loss_no_weight_decay: 1.0982
— val_kappa: 0.0 

Epoch 00004: val_kappa did not improve from 0.00000
Confusion matrix: 
 [[23  0  0]
 [ 6  0  0]
 [23  0  0]]
Epoch 5/50
9/9 [==============================] - 19s 2s/step - loss: 1.0973 - acc: 0.4356 - binary_accuracy: 0.6667 - mean_abs

9/9 [==============================] - 19s 2s/step - loss: 1.0824 - acc: 0.3720 - binary_accuracy: 0.6667 - mean_absolute_error: 0.4444 - loss_no_weight_decay: 1.0824 - val_loss: 1.0989 - val_acc: 0.3125 - val_binary_accuracy: 0.6667 - val_mean_absolute_error: 0.4445 - val_loss_no_weight_decay: 1.0989
— val_kappa: 0.0 

Epoch 00021: val_kappa did not improve from 0.00000
Confusion matrix: 
 [[21  0  0]
 [ 9  0  0]
 [22  0  0]]
Epoch 22/50
9/9 [==============================] - 19s 2s/step - loss: 1.0991 - acc: 0.3828 - binary_accuracy: 0.6667 - mean_absolute_error: 0.4444 - loss_no_weight_decay: 1.0991 - val_loss: 1.0979 - val_acc: 0.4231 - val_binary_accuracy: 0.6667 - val_mean_absolute_error: 0.4443 - val_loss_no_weight_decay: 1.0979
— val_kappa: 0.0 

Epoch 00022: val_kappa did not improve from 0.00000

Epoch 00022: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Confusion matrix: 
 [[27  0  0]
 [ 9  0  0]
 [16  0  0]]
Epoch 23/50
9/9 [============================

9/9 [==============================] - 19s 2s/step - loss: 1.0998 - acc: 0.3589 - binary_accuracy: 0.6667 - mean_absolute_error: 0.4443 - loss_no_weight_decay: 1.0998 - val_loss: 1.0979 - val_acc: 0.3438 - val_binary_accuracy: 0.6667 - val_mean_absolute_error: 0.4443 - val_loss_no_weight_decay: 1.0979
— val_kappa: 0.0 

Epoch 00039: val_kappa did not improve from 0.00000
Confusion matrix: 
 [[29  0  0]
 [ 7  0  0]
 [16  0  0]]
Epoch 40/50
9/9 [==============================] - 19s 2s/step - loss: 1.1004 - acc: 0.3878 - binary_accuracy: 0.6667 - mean_absolute_error: 0.4442 - loss_no_weight_decay: 1.1004 - val_loss: 1.0980 - val_acc: 0.3462 - val_binary_accuracy: 0.6667 - val_mean_absolute_error: 0.4443 - val_loss_no_weight_decay: 1.0980
— val_kappa: 0.0 

Epoch 00040: val_kappa did not improve from 0.00000
Confusion matrix: 
 [[31  0  0]
 [ 5  0  0]
 [16  0  0]]
Epoch 41/50
9/9 [==============================] - 20s 2s/step - loss: 1.0889 - acc: 0.3570 - binary_accuracy: 0.6667 - mean_a

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
